name: SEO Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  seo-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run SEO audit
      run: npm run check
      
    - name: Upload audit artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: seo-audit-reports
        path: |
          docs/
        retention-days: 30
        
    - name: Comment PR with summary
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          try {
            const summaryPath = path.join(process.env.GITHUB_WORKSPACE, 'docs/SUMMARY.md');
            
            if (fs.existsSync(summaryPath)) {
              const summary = fs.readFileSync(summaryPath, 'utf8');
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🔍 SEO Audit Results\n\n${summary}\n\n---\n*View detailed reports in the [artifacts](${context.payload.pull_request.html_url}/checks) of this workflow run.*`
              });
            }
          } catch (error) {
            console.log('Could not post PR comment:', error.message);
          }